/*****************************************************************************/
/*                      BEGIN libcdada AUTOGENERATED C++ file                */
/*****************************************************************************/
// File autogenerated from cmd: ['/home/toto/Projects/libcdada/tools/cdada-gen', 'list:ptm_label', '-o', 'autogen_cdada_ptm_label.cc']
// Add your header includes for types {'ptm_label'} here

#include "cdada_types/ptm_label.h"

///////////////////////////////////////////////////////////////////////////////
///                       DO NOT MODIFY AFTER THIS LINE                     ///
///////////////////////////////////////////////////////////////////////////////

#include <string.h>
#include <cdada/list_custom_cc.h>
#include <cdada/map_custom_cc.h>
#include <cdada/queue_custom_cc.h>
#include <cdada/set_custom_cc.h>
#include <cdada/stack_custom_cc.h>

//C++ comparison operators for user stypes (memcmp)

inline bool operator<(const ptm_label & a1, const ptm_label & a2){
    return memcmp((const void*)&a1, (const void*)&a2,
                                        sizeof( ptm_label )) < 0;
}
inline bool operator==(const ptm_label & a1, const ptm_label & a2){
    return memcmp((const void*)&a1, (const void*)&a2,
                                        sizeof( ptm_label )) == 0;
}

//Cdata wrappers

//BEGIN list for ptm_label (std::list<ptm_label>)


//Operator
void __cdada_list_autogen_create_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	s->list.custom = (void*)new std::list<ptm_label>();
}
void __cdada_list_autogen_destroy_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	delete p;
}
void __cdada_list_autogen_clear_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	p->clear();
}
bool __cdada_list_autogen_empty_ptm_label (const void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return p->empty();
}
uint32_t __cdada_list_autogen_size_ptm_label (const void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return p->size();
}
int __cdada_list_autogen_insert_ptm_label (void* m, const void* val,
						const uint32_t pos){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_insert_u<ptm_label> (s, p, val, pos);
}
int __cdada_list_autogen_get_ptm_label (const void* m, const uint32_t pos,
						void* val){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_get_u<ptm_label> (s, p, pos, val);
}
int __cdada_list_autogen_first_last_ptm_label (const void* m, bool first,
						void* key){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_first_last_u<ptm_label> (s, p, first, key);
}
int __cdada_list_autogen_erase_ptm_label (void* m, const uint32_t pos){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_erase_u<ptm_label> (s, p, pos);
}
int __cdada_list_autogen_remove_ptm_label (void* m, const void* val){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_remove_u<ptm_label> (s, p, val);
}
int __cdada_list_autogen_push_ptm_label (void* m, const void* val,
							bool front){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_push_u<ptm_label> (s, p, val, front);
}
int __cdada_list_autogen_pop_ptm_label (void* m, bool front){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_pop_u<ptm_label> (s, p, front);
}
void __cdada_list_autogen_sort_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	p->sort();
}
void __cdada_list_autogen_reverse_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	p->reverse();
}
void __cdada_list_autogen_unique_ptm_label (void* m){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	p->unique();
}
void __cdada_list_autogen_traverse_ptm_label (const void* m,
						cdada_list_it f,
						void* opaque){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_traverse_u<ptm_label> (s, p, f, opaque);
}
void __cdada_list_autogen_rtraverse_ptm_label (const void* m,
						cdada_list_it f,
						void* opaque){
	__cdada_list_int_t* s = (__cdada_list_int_t*)m;
	std::list<ptm_label>* p =
			(std::list<ptm_label>*)s->list.custom;
	return cdada_list_rtraverse_u<ptm_label> (s, p, f, opaque);
}
void __cdada_list_autogen_dump_ptm_label (const void* m,
                                                std::stringstream& ss){
        __cdada_list_int_t* s = (__cdada_list_int_t*)m;
        std::list<ptm_label>* p =
                        (std::list<ptm_label>*)s->list.custom;
        return cdada_list_dump_u< ptm_label > (s, p, ss);
}
__cdada_list_ops_t __cdada_list_autogen_ptm_label = {
	__cdada_list_autogen_create_ptm_label,
	__cdada_list_autogen_destroy_ptm_label,
	__cdada_list_autogen_clear_ptm_label,
	__cdada_list_autogen_empty_ptm_label,
	__cdada_list_autogen_size_ptm_label,
	__cdada_list_autogen_insert_ptm_label,
	__cdada_list_autogen_get_ptm_label,
	__cdada_list_autogen_first_last_ptm_label,
	__cdada_list_autogen_erase_ptm_label,
	__cdada_list_autogen_remove_ptm_label,
	__cdada_list_autogen_push_ptm_label,
	__cdada_list_autogen_pop_ptm_label,
	__cdada_list_autogen_sort_ptm_label,
	__cdada_list_autogen_reverse_ptm_label,
	__cdada_list_autogen_unique_ptm_label,
	__cdada_list_autogen_traverse_ptm_label,
	__cdada_list_autogen_rtraverse_ptm_label,
	__cdada_list_autogen_dump_ptm_label,
};

//END list for ptm_label (std::list<ptm_label>)

/*****************************************************************************/
/*                       END libcdada AUTOGENERATED C++ file                 */
/*****************************************************************************/
